services:

  postgres:
    container_name: keycloakdb
    volumes:
      - "postgres_data:/D:/Users/bahma/OneDrive/Documents/FORMATIONS/Udemy-formation/volumes/keycloak"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: keycloak
    extends:
      file: common-config.yml
      service: keycloak-db-config

  keycloak:
    #image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    build:
      context: .
      args:
        KEYCLOAK_VERSION: 22.0.0
    command: [ 'start', '--optimized', '--import-realm' ]
    depends_on:
      - "postgres"
    ports:
      - "7080:8080"
      - "8787:8787" # debug port
    environment:
      JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.upload_scripts=enabled"
      KC_DB_PASSWORD: "postgres"
      KC_DB_URL: "jdbc:postgresql://postgres/keycloak"
      KC_DB_USERNAME: "postgres"
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HOSTNAME_URL: "http://localhost:7080"
      KC_PROXY: "reencrypt"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KEYCLOAK_IMPORT: "/opt/keycloak/data/import/realm.json"
    volumes:
      - ./auth/import:/opt/keycloak/data/import
    extends:
      file: common-config.yml
      service: network-deploy-service

networks:
  mamadou4bah:
    driver: "bridge"

volumes:
  postgres_data: